### ISSUE TITLE
Grey out PWAs that are not available offline.

### ISSUE THREAD

**Issue by juliantoledo** [GoogleChrome/gulliver#108]
We should grey out (or icon, title, etc) PWAs that are not available offline

**Comment by ithinkihaveacat** [comment]
This should be reasonably straightforward to do now. The steps are:

- [ ] Add `.gulliver-signin-aware` to the elements that needs to be greyed out/transformed.
- [ ] Modify [`gulliver.js`](https://github.com/GoogleChrome/gulliver/blob/master/public/js/gulliver.js#L147) so that it transforms the elements as appropriate.

I can easily do this though maybe it's worthwhile for someone else to look in more detail at how the state-tracking systems work, and whether it can be improved?

**Comment by ithinkihaveacat** [comment]
This should be fixed by #111.
