### ISSUE TITLE
Old urls show double header

### ISSUE THREAD

**Issue by juliantoledo** [GoogleChrome/gulliver#403]
Our old urls cause a double header in the new PRPL implementation:
https://pwa-directory.appspot.com/pwas/5168969224814592#t=Vitor%20Alencar&bg=%23462373&c=%23ffffff
![screen shot 2017-05-15 at 1 55 59 pm](https://cloud.githubusercontent.com/assets/1920764/26056597/576c53be-3976-11e7-9801-6e86ec3fba58.png)

**Comment by juliantoledo** [comment]
@andreban is it a problem in our router?

**Comment by andreban** [comment]
The problem is when deriving the contentOnly URL. It's appending the ?contentOnly=true after the hash, so the parameter is being ignored when the request is made to the browser. 

[This method](https://github.com/GoogleChrome/gulliver/blob/master/public/js/routing/route.js#L48-L50) needs to be updated to cover this.
