### ISSUE TITLE
Invalid PWA URL shows double-404 page

### ISSUE THREAD

**Issue by samthor** [GoogleChrome/gulliver#416]
e.g.- https://pwa-directory.appspot.com/pwas/fasfsafdsa

shows-
![screen shot 2017-06-13 at 18 09 36](https://user-images.githubusercontent.com/119184/27072333-7a20bf68-5063-11e7-8d15-c5add19bd0f4.png)

**Comment by juliantoledo** [comment]
@andreban is it a router issue?

**Comment by andreban** [comment]
The issue seems to be in the backend. Requesting `https://pwa-directory.appspot.com/asdasdsad` triggers a call to `https://pwa-directory.appspot.com/asdasdsad?contentOnly=true`, which is correct. 

Looks like [404.hbs](https://github.com/GoogleChrome/gulliver/blob/master/views/404.hbs) is not aware to `contentOnly` at all.
